// lion_core/src/neuron.rs

use crate::constants::{
    FEATURE_SIZE, MAX_TRACES, OVERLOAD_THRESHOLD, TRACE_DECAY_RATE,
};
use crate::types::{GenIndex, MemoryTrace, Role};
use serde::{Deserialize, Serialize};

// =============================================================================
// ACTION LABEL
// =============================================================================

/// A fixed-size UTF-8 label for MOTOR neurons.
///
/// Replaces Python's `action_label: Optional[str]`.
/// Fixed to 16 bytes so Neuron remains `Copy`-compatible in the future.
///
/// Stored as raw bytes internally. Use `ActionLabel::as_str()` to read.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct ActionLabel {
    bytes: [u8; 16],
    len:   u8,
}

impl ActionLabel {
    /// Creates an ActionLabel from a string slice.
    /// Panics at compile time if the string exceeds 16 bytes.
    pub fn new(s: &str) -> Self {
        let bytes_src = s.as_bytes();
        assert!(
            bytes_src.len() <= 16,
            "ActionLabel '{}' exceeds 16 bytes",
            s
        );
        let mut bytes = [0u8; 16];
        let len = bytes_src.len();
        bytes[..len].copy_from_slice(bytes_src);
        Self { bytes, len: len as u8 }
    }

    /// Returns the label as a string slice.
    pub fn as_str(&self) -> &str {
        std::str::from_utf8(&self.bytes[..self.len as usize])
            .unwrap_or("INVALID")
    }
}

// =============================================================================
// NEURON
// =============================================================================

/// The core cognitive unit of LionAI.
///
/// Translates Python's `NeuronNode` into a fully arena-compatible,
/// fixed-size Rust struct.
///
/// CRITICAL DESIGN RULE:
/// No heap allocations inside Neuron.
/// `traces` is a fixed array of `[MemoryTrace; MAX_TRACES]`.
/// `trace_count` tracks how many slots are occupied.
/// This makes `Neuron` trivially cloneable for the night cycle.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Neuron {
    /// Generational index — the neuron's identity inside the BrainMatrix arena.
    pub id: GenIndex,

    /// Biological role — determines which sensory inputs activate this neuron.
    pub role: Role,

    /// Current activation signal. Range: [-1.0, +1.0] via tanh.
    /// Matches Python: self.activation: float = 0.0
    pub activation: f32,

    /// The neuron's intrinsic feature representation.
    /// Initialized with small random values. Never zeroed after construction.
    /// Matches Python: self.base_vector: np.ndarray = np.random.uniform(-0.1, 0.1, dna.feature_size)
    pub base_vector: [f32; FEATURE_SIZE],

    /// Fixed-size episodic memory trace bank.
    /// Slots 0..trace_count are active. Slots trace_count..MAX_TRACES are empty.
    /// Matches Python: self.local_traces: List[MemoryTrace] = []
    pub traces: [MemoryTrace; MAX_TRACES],

    /// Number of active traces currently stored. Range: 0..=MAX_TRACES.
    pub trace_count: usize,

    /// Evolutionary generation counter. Increments on mitosis.
    /// Matches Python: self.generation: int = 0
    pub generation: u32,

    /// Optional action label. Only set for Role::Motor neurons.
    /// Matches Python: self.action_label = action_label
    pub action_label: Option<ActionLabel>,

    /// Whether this neuron is alive. False = dead slot available for reuse.
    /// Matches Python: neurons are deleted from the dict on death.
    pub alive: bool,
}

impl Neuron {
    /// Constructs a new live neuron with a given role and pre-computed base vector.
    ///
    /// The `id` is assigned by the `BrainMatrix` arena after slot allocation.
    /// The `base_vector` should be generated by the arena's RNG before calling this.
    pub fn new(id: GenIndex, role: Role, base_vector: [f32; FEATURE_SIZE]) -> Self {
        Self {
            id,
            role,
            activation:   0.0,
            base_vector,
            traces:       [MemoryTrace::default(); MAX_TRACES],
            trace_count:  0,
            generation:   0,
            action_label: None,
            alive:        true,
        }
    }

    // -------------------------------------------------------------------------
    // ACTIVATION
    // -------------------------------------------------------------------------

    /// Computes tanh activation from an input sum and stores it.
    ///
    /// Matches Python:
    ///   def process_activation(self, input_sum: float):
    ///       self.activation = np.tanh(input_sum)
    pub fn process_activation(&mut self, input_sum: f32) {
        self.activation = input_sum.tanh();
    }

    /// Resets activation to zero between ticks.
    ///
    /// Matches Python: NeuralGraph.reset_activations()
    pub fn reset_activation(&mut self) {
        self.activation = 0.0;
    }

    // -------------------------------------------------------------------------
    // MEMORY TRACES
    // -------------------------------------------------------------------------

    /// Adds a new memory trace, decays all existing traces, and evicts the
    /// weakest trace if the bank is full.
    ///
    /// Matches Python:
    ///   def add_trace(self, vector: np.ndarray):
    ///       for t in self.local_traces:
    ///           t.age += 1
    ///           t.strength *= self.dna.trace_decay_rate
    ///       new_trace = MemoryTrace(...)
    ///       if len(self.local_traces) >= self.dna.max_neuron_traces:
    ///           weakest_idx = min(...)
    ///           self.local_traces.pop(weakest_idx)
    ///       self.local_traces.append(new_trace)
    pub fn add_trace(&mut self, vector: [f32; FEATURE_SIZE]) {
        // Step 1: Decay all existing active traces.
        for i in 0..self.trace_count {
            self.traces[i].age      += 1;
            self.traces[i].strength *= TRACE_DECAY_RATE;
        }

        let new_trace = MemoryTrace::new(vector);

        if self.trace_count < MAX_TRACES {
            // Step 2a: Bank has empty slots. Append directly.
            self.traces[self.trace_count] = new_trace;
            self.trace_count += 1;
        } else {
            // Step 2b: Bank is full. Overwrite the weakest trace.
            let weakest_idx = self.weakest_trace_index();
            self.traces[weakest_idx] = new_trace;
        }
    }

    /// Returns the index of the active trace with the lowest strength.
    /// Only call this when `trace_count == MAX_TRACES`.
    fn weakest_trace_index(&self) -> usize {
        (0..self.trace_count)
            .min_by(|&a, &b| {
                self.traces[a]
                    .strength
                    .partial_cmp(&self.traces[b].strength)
                    .unwrap_or(std::cmp::Ordering::Equal)
            })
            .unwrap_or(0)
    }

    /// Returns a slice of only the active (occupied) trace slots.
    pub fn active_traces(&self) -> &[MemoryTrace] {
        &self.traces[..self.trace_count]
    }

    /// Returns the most recently written trace, if any.
    /// Used by Hebbian plasticity to compare trace alignment between neurons.
    pub fn latest_trace(&self) -> Option<&MemoryTrace> {
        if self.trace_count == 0 {
            None
        } else {
            // The most recent trace is always appended last in the active window.
            // Because eviction overwrites the weakest (not necessarily the last),
            // we scan for the youngest (age == 0 or minimum age).
            let youngest_idx = (0..self.trace_count)
                .min_by_key(|&i| self.traces[i].age)
                .unwrap_or(0);
            Some(&self.traces[youngest_idx])
        }
    }

    // -------------------------------------------------------------------------
    // OVERLOAD CHECK (MITOSIS ELIGIBILITY)
    // -------------------------------------------------------------------------

    /// Returns true if this neuron is eligible for mitosis (cell division).
    ///
    /// Conditions:
    ///   1. The trace bank must be completely full (trace_count == MAX_TRACES).
    ///   2. The average trace strength must exceed OVERLOAD_THRESHOLD (0.8).
    ///
    /// Matches Python:
    ///   def is_overloaded(self) -> bool:
    ///       if len(self.local_traces) < self.dna.max_neuron_traces: return False
    ///       avg_str = sum(t.strength for t in self.local_traces) / len(self.local_traces)
    ///       return avg_str > 0.8
    pub fn is_overloaded(&self) -> bool {
        if self.trace_count < MAX_TRACES {
            return false;
        }

        let avg_strength: f32 = self.traces[..MAX_TRACES]
            .iter()
            .map(|t| t.strength)
            .sum::<f32>()
            / MAX_TRACES as f32;

        avg_strength > OVERLOAD_THRESHOLD
    }
}
